// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/nohponex/clean-architecture/internal/simplebank/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// AccessService is an autogenerated mock type for the AccessService type
type AccessService struct {
	mock.Mock
}

// PersonHasAccessToAccount provides a mock function with given fields: ctx, person, account
func (_m *AccessService) PersonHasAccessToAccount(ctx context.Context, person model.PersonID, account model.AccountID) (bool, error) {
	ret := _m.Called(ctx, person, account)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context, model.PersonID, model.AccountID) bool); ok {
		r0 = rf(ctx, person, account)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.PersonID, model.AccountID) error); ok {
		r1 = rf(ctx, person, account)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
