version: '3'
services:
  http:
    volumes:
      - .:/app
      - ./assets/db/migrations:/migrations
    build:
      context: .
      dockerfile: build/dockerfiles/Dockerfile.dev
    command: /http
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    restart: on-failure
    ports:
      - "40000:40000"
      - "8080:8080"
    environment:
      - CGO_ENABLED=0
      - AMQ_USERNAME=admin
      - AMQ_PASSWORD=password
      - AMQ_HOST=rabbitmq
      - AMQ_PORT=5672
      - AMQ_VHOST=/
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_ERLANG_COOKIE=cluster_cookie
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_DEFAULT_VHOST=/
