// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Messaging is an autogenerated mock type for the Messaging type
type Messaging struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, eventType, body
func (_m *Messaging) Publish(ctx context.Context, eventType string, body map[string]interface{}) error {
	ret := _m.Called(ctx, eventType, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) error); ok {
		r0 = rf(ctx, eventType, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
