GET http://localhost:8080/account/{{acountID}}/open
Accept: application/json
Authorization: {{personID}}

###

GET http://localhost:8080/account/{{acountID}}
Accept: application/json
Authorization: {{personID}}

###

GET http://localhost:8080/account/{{acountID}}/withdraw/500
Accept: application/json
Authorization: {{personID}}

###

GET http://localhost:8080/account/{{acountID}}/topup/500
Accept: application/json
Authorization: {{personID}}

###
